### ISSUE TITLE
dbt install error

### ISSUE THREAD

**Issue by a-aguilera** [fishtown-analytics/homebrew-dbt#2]
Hi! I'm getting this error after running brew install dbt

```==> /usr/local/Cellar/dbt/0.10.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cryptography-20180718-25581-1w80mze/crypt
Last 15 lines from /Users/abrahamaguilera/Library/Logs/Homebrew/dbt/20.pip:
  Removing source in /private/tmp/pip-req-build-kmkUsB
Command "/usr/local/Cellar/dbt/0.10.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-kmkUsB/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-Kq5P0O/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/dbt/0.10.1/libexec/include/site/python2.7/cryptography" failed with error code 1 in /private/tmp/pip-req-build-kmkUsB/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/dbt/0.10.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-kmkUsB/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-Kq5P0O/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/dbt/0.10.1/libexec/include/site/python2.7/cryptography" failed with error code 1 in /private/tmp/pip-req-build-kmkUsB/
```

Also, I tried brew update and brew reinstall dbt and got this:

```==> /usr/local/Cellar/dbt/0.10.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cryptography-20180718-26596-1uvdiei/crypt
Last 15 lines from /Users/abrahamaguilera/Library/Logs/Homebrew/dbt/20.pip:
  Removing source in /private/tmp/pip-req-build-ttCT8Y
Command "/usr/local/Cellar/dbt/0.10.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-ttCT8Y/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-g4ekAU/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/dbt/0.10.1/libexec/include/site/python2.7/cryptography" failed with error code 1 in /private/tmp/pip-req-build-ttCT8Y/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/dbt/0.10.1/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/dbt/0.10.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-ttCT8Y/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-g4ekAU/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/dbt/0.10.1/libexec/include/site/python2.7/cryptography" failed with error code 1 in /private/tmp/pip-req-build-ttCT8Y/
```

**Comment by cmcarthur** [comment]
Hi @a-aguilera ! what versions of macos and xcode do you have installed?

**Comment by kstarsinic** [comment]
I just had the same error with Mac OS 10.12.6, Xcode 9.2 (Build version 9C40b).

**Comment by a-aguilera** [comment]
Thanks for your response! I thought it might have been an OS issue so I’m updating right now both the MacOS and Xcode to the latest versions. About 30 minutes remaining. I’ll try again as soon as it’s done and get back to you guys

**Comment by cmcarthur** [comment]
this is the result of a patch fix for https://github.com/fishtown-analytics/homebrew-dbt/issues/1
